// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_cumsum_init
NumericVector rcpp_cumsum_init(NumericVector x, double initial_value);
RcppExport SEXP _RandomWalker_rcpp_cumsum_init(SEXP xSEXP, SEXP initial_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type initial_value(initial_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_cumsum_init(x, initial_value));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_cumprod_init
NumericVector rcpp_cumprod_init(NumericVector x, double initial_value);
RcppExport SEXP _RandomWalker_rcpp_cumprod_init(SEXP xSEXP, SEXP initial_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type initial_value(initial_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_cumprod_init(x, initial_value));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_cummin_init
NumericVector rcpp_cummin_init(NumericVector x, double initial_value);
RcppExport SEXP _RandomWalker_rcpp_cummin_init(SEXP xSEXP, SEXP initial_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type initial_value(initial_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_cummin_init(x, initial_value));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_cummax_init
NumericVector rcpp_cummax_init(NumericVector x, double initial_value);
RcppExport SEXP _RandomWalker_rcpp_cummax_init(SEXP xSEXP, SEXP initial_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type initial_value(initial_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_cummax_init(x, initial_value));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_cummean_init
NumericVector rcpp_cummean_init(NumericVector x, double initial_value);
RcppExport SEXP _RandomWalker_rcpp_cummean_init(SEXP xSEXP, SEXP initial_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type initial_value(initial_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_cummean_init(x, initial_value));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_batch_cumstats
NumericMatrix rcpp_batch_cumstats(NumericVector x, double initial_value);
RcppExport SEXP _RandomWalker_rcpp_batch_cumstats(SEXP xSEXP, SEXP initial_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type initial_value(initial_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_batch_cumstats(x, initial_value));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RandomWalker_rcpp_cumsum_init", (DL_FUNC) &_RandomWalker_rcpp_cumsum_init, 2},
    {"_RandomWalker_rcpp_cumprod_init", (DL_FUNC) &_RandomWalker_rcpp_cumprod_init, 2},
    {"_RandomWalker_rcpp_cummin_init", (DL_FUNC) &_RandomWalker_rcpp_cummin_init, 2},
    {"_RandomWalker_rcpp_cummax_init", (DL_FUNC) &_RandomWalker_rcpp_cummax_init, 2},
    {"_RandomWalker_rcpp_cummean_init", (DL_FUNC) &_RandomWalker_rcpp_cummean_init, 2},
    {"_RandomWalker_rcpp_batch_cumstats", (DL_FUNC) &_RandomWalker_rcpp_batch_cumstats, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RandomWalker(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
