# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast Cumulative Sum with Initial Value
#'
#' This function computes the cumulative sum of a numeric vector with an initial value offset.
#' Implemented in C++ for improved performance.
#'
#' @param x A numeric vector
#' @param initial_value A numeric value to add to all cumulative sums
#' @return A numeric vector of cumulative sums
#' @export
rcpp_cumsum_init <- function(x, initial_value = 0.0) {
    .Call('_RandomWalker_rcpp_cumsum_init', PACKAGE = 'RandomWalker', x, initial_value)
}

#' Fast Cumulative Product with Initial Value
#'
#' This function computes the cumulative product of (1 + x) multiplied by initial value.
#' Implemented in C++ for improved performance.
#'
#' @param x A numeric vector
#' @param initial_value A numeric value to multiply with cumulative products
#' @return A numeric vector of cumulative products
#' @export
rcpp_cumprod_init <- function(x, initial_value = 1.0) {
    .Call('_RandomWalker_rcpp_cumprod_init', PACKAGE = 'RandomWalker', x, initial_value)
}

#' Fast Cumulative Minimum with Initial Value
#'
#' This function computes the cumulative minimum of a numeric vector with an initial value offset.
#' Implemented in C++ for improved performance.
#'
#' @param x A numeric vector
#' @param initial_value A numeric value to add to all cumulative minimums
#' @return A numeric vector of cumulative minimums
#' @export
rcpp_cummin_init <- function(x, initial_value = 0.0) {
    .Call('_RandomWalker_rcpp_cummin_init', PACKAGE = 'RandomWalker', x, initial_value)
}

#' Fast Cumulative Maximum with Initial Value
#'
#' This function computes the cumulative maximum of a numeric vector with an initial value offset.
#' Implemented in C++ for improved performance.
#'
#' @param x A numeric vector
#' @param initial_value A numeric value to add to all cumulative maximums
#' @return A numeric vector of cumulative maximums
#' @export
rcpp_cummax_init <- function(x, initial_value = 0.0) {
    .Call('_RandomWalker_rcpp_cummax_init', PACKAGE = 'RandomWalker', x, initial_value)
}

#' Fast Cumulative Mean with Initial Value
#'
#' This function computes the cumulative mean of a numeric vector with an initial value offset.
#' Implemented in C++ for improved performance.
#'
#' @param x A numeric vector
#' @param initial_value A numeric value to add to all cumulative means
#' @return A numeric vector of cumulative means
#' @export
rcpp_cummean_init <- function(x, initial_value = 0.0) {
    .Call('_RandomWalker_rcpp_cummean_init', PACKAGE = 'RandomWalker', x, initial_value)
}

#' Batch Cumulative Statistics
#'
#' This function computes all cumulative statistics (sum, prod, min, max, mean) 
#' in a single pass for better cache efficiency.
#' Implemented in C++ for improved performance.
#'
#' @param x A numeric vector
#' @param initial_value A numeric value for initial offset
#' @return A numeric matrix with 5 columns: cum_sum, cum_prod, cum_min, cum_max, cum_mean
#' @export
rcpp_batch_cumstats <- function(x, initial_value = 0.0) {
    .Call('_RandomWalker_rcpp_batch_cumstats', PACKAGE = 'RandomWalker', x, initial_value)
}

